#!/bin/bash

# SPDX-License-Identifier: Apache-2.0
# Yui is a tool to summon guest initrd images for Kata Containers

if [[ $1 == "" ]]; then
        echo usage: $0 app
        exit 1
fi


ROOT=$(realpath $(dirname $0))
CUSTOM_QEMU=${CUSTOM_QEMU:-0}
APP=$1

set -e

QEMU="/opt/azucatemu/bin/qemu-system-x86_64"
KERNEL="/root/yui/vmlinux.yui"
INITRD="${ROOT}/${APP}.cpio.gz"
echo "Using kernel: ${KERNEL}"
echo "Using initrd: ${INITRD}"

exec ${QEMU} \
-enable-kvm -display none \
-machine q35,accel=kvm,nvdimm=on \
-cpu host,pmu=off,xsave=off \
-m 2048M,slots=10,maxmem=128939M \
-smp 1,cores=1,threads=1,sockets=1,maxcpus=1 \
-append "console=ttyS0" \
-bios /opt/kata/share/kata-qemu/qemu/qboot.rom \
-initrd "${ROOT}/apps/${APP}.cpio.gz" \
-kernel ${KERNEL} \
-serial stdio 
