#!/bin/bash

ROOT=$(realpath "$(dirname "$(realpath "$0")")/..")
CONFIG="$ROOT/configs/host_x86_64_defconfig"
BUILD="$ROOT/build/host"

set -e 

mkdir -p "${BUILD}"
make -C "${ROOT}/linux" O="${BUILD}" KCONFIG_CONFIG="$CONFIG" olddefconfig
exec make -C "${ROOT}/linux" O="${BUILD}" KCONFIG_CONFIG="$CONFIG" -j$(nproc)
